name: Build Status

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ""
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "v18.18.0"
          registry-url: "https://registry.npmjs.org"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install Python dependencies
        run: |
          poetry update
          poetry install
      - name: Install Node dependencies
        run: npm install
      - run: cp .env.example .env
      - name: Run Node lints
        run: npm run lint
      - name: Run Python lints
        run: poetry run flask lint --check
      - name: Run Python tests
        run: poetry run flask test
